/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package libreria_app;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.awt.Toolkit;

/**
 *
 * @author manolo
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegstro
     */
    public VentanaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        registronombre = new javax.swing.JTextField();
        registrorut = new javax.swing.JTextField();
        registrodireccion = new javax.swing.JTextField();
        registrotelefono = new javax.swing.JTextField();
        registrousuario = new javax.swing.JTextField();
        registropass = new javax.swing.JTextField();
        botonregistro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Usuarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese los siguientes datos para registrarse en el sistema:");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Rut:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Dirección");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Usuario");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Contraseña");

        registronombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registronombreActionPerformed(evt);
            }
        });
        registronombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registronombreKeyTyped(evt);
            }
        });

        registrorut.setMaximumSize(new java.awt.Dimension(9, 9));
        registrorut.setMinimumSize(new java.awt.Dimension(8, 9));
        registrorut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrorutActionPerformed(evt);
            }
        });
        registrorut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registrorutKeyTyped(evt);
            }
        });

        registrodireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registrodireccionKeyTyped(evt);
            }
        });

        registrotelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrotelefonoActionPerformed(evt);
            }
        });
        registrotelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registrotelefonoKeyTyped(evt);
            }
        });

        registrousuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registrousuarioKeyTyped(evt);
            }
        });

        registropass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registropassKeyTyped(evt);
            }
        });

        botonregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/110765-glowing-green-neon-icon-alphanumeric-plus-sign-simple-36x36.png"))); // NOI18N
        botonregistro.setText("ingresar");
        botonregistro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        botonregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregistroActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel8.setText("Ej: 91119993");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(215, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(registronombre)
                                        .addGap(63, 63, 63))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(registrorut, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                            .addComponent(registrodireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(registrotelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(registrousuario, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(registropass, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(botonregistro)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(registronombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(registrorut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrodireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(registrotelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(registrousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(registropass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registronombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registronombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registronombreActionPerformed

    private void botonregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregistroActionPerformed
        // TODO add your handling code here:
        conexion cn=new conexion();
        
        if(registronombre.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "El campo de texto 'Nombre' está vacío");
            }
        String nombre=registronombre.getText();
        if(registrorut.getText().trim().length()==0 | registrorut.getText().trim().length()<8 |
                registrorut.getText().trim().length()>9){
            JOptionPane.showMessageDialog(this, "El campo de texto 'Rut' está incorrecto");
           }
        String rut=registrorut.getText();
        if(registrodireccion.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "El campo de texto 'Dirección' está vacío");}
        String direccion=registrodireccion.getText();
        if(registrotelefono.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "El campo de texto 'Teléfono' está vacío");}
        String telefono=registrotelefono.getText();
        int numero = Integer.parseInt(telefono);// convertir a entero
        if(registrousuario.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "El campo de texto 'Usuario está vacío");}
        String usuario=registrousuario.getText();
        if(registropass.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "El campo de texto 'Pass' está vacío");}
        String pass=registropass.getText();
        try{ 
        if (nombre.length()>0 && rut.length()>=8 && direccion.length()>0 && telefono.length()>0 && usuario.length()>0){
            cn.setEsSelect(false);
                cn.setComandoSQL("insert into usuario (rut, nombre, direccion, telefono, usuarioingreso, contraseña) values('"+rut+"', '"+nombre+"', '"+direccion+"','"+numero+"','"+usuario+"','"+pass+"')");
                cn.conectar();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                cn.cerrarConexion();
                JOptionPane.showMessageDialog(this, "Los datos fueron ingresados correctamente");
                VentanaPrincipal v=new VentanaPrincipal();
                this.dispose();
                }
            }     
        catch(HeadlessException e){
               System.out.println("Se ha producido un error " + e );
        }
    }//GEN-LAST:event_botonregistroActionPerformed

    private void registrotelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrotelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrotelefonoActionPerformed

    private void registrotelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrotelefonoKeyTyped
    if (registrotelefono.getText().length()== 8){
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
    } 
    if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()))
    {
     Toolkit.getDefaultToolkit().beep();
     JOptionPane.showMessageDialog(this, "Ingrese solo numeros");
     evt.consume();
        }        // Evento para entrar solo numeros
    }//GEN-LAST:event_registrotelefonoKeyTyped
    
    private void registrorutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrorutKeyTyped
    String text=registrorut.getText();
    if (text.length()== 9){
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
    }    
    char car = evt.getKeyChar();
    if(!Character.isDigit(evt.getKeyChar()) && car!='k')
    {
     Toolkit.getDefaultToolkit().beep();
     JOptionPane.showMessageDialog(this, "Ingrese solo numeros");
     evt.consume();
        }        // Evento para entrar solo numeros       // TODO add your handling code here:
    }//GEN-LAST:event_registrorutKeyTyped

    private void registrorutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrorutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrorutActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         VentanaPrincipal v=new VentanaPrincipal();
         v.setLocationRelativeTo(null);
         v.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void registropassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registropassKeyTyped
    if (registrorut.getText().length()== 19){
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
    }           // TODO add your handling code here:
    }//GEN-LAST:event_registropassKeyTyped

    private void registrousuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrousuarioKeyTyped
    if (registrorut.getText().length()== 20){
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
    }           // TODO add your handling code here:
    }//GEN-LAST:event_registrousuarioKeyTyped

    private void registronombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registronombreKeyTyped
    if (registrorut.getText().length()== 99){
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
    }           // TODO add your handling code here:
    }//GEN-LAST:event_registronombreKeyTyped

    private void registrodireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrodireccionKeyTyped
    if (registrorut.getText().length()== 99){
    evt.consume();
    Toolkit.getDefaultToolkit().beep();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_registrodireccionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonregistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField registrodireccion;
    public javax.swing.JTextField registronombre;
    public javax.swing.JTextField registropass;
    public javax.swing.JTextField registrorut;
    public javax.swing.JTextField registrotelefono;
    public javax.swing.JTextField registrousuario;
    // End of variables declaration//GEN-END:variables
}
