/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package libreria_app;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author manolo
 */
public class VentanaRegistroLibro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistroLibro
     */
    public VentanaRegistroLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ingresoingresolibro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        titulolibro = new javax.swing.JLabel();
        registrotitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        registroedicion = new javax.swing.JTextField();
        botoningresolibro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        registrotelefonoeditorial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        registronombreeditorial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        registrodireccioneditorial = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        registronacionalidadautor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        registronombreautor = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        registroestadolibro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        registrogenerolibro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        registrocategorialibro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        añodeimpresion = new javax.swing.JTextField();
        ingresoatras = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        registropreciolibro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Ingreso De Libro");

        ingresoingresolibro.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ingresoingresolibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/110765-glowing-green-neon-icon-alphanumeric-plus-sign-simple-36x36.png"))); // NOI18N
        ingresoingresolibro.setText("Agregar");
        ingresoingresolibro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ingresoingresolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoingresolibroActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 10))); // NOI18N

        titulolibro.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        titulolibro.setText("Titulo Libro");

        registrotitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrotituloActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Edicion Libro");

        botoningresolibro.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        botoningresolibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/110765-glowing-green-neon-icon-alphanumeric-plus-sign-simple-36x36.png"))); // NOI18N
        botoningresolibro.setText("Agregar");
        botoningresolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoningresolibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registrotitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(registroedicion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botoningresolibro, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botoningresolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulolibro)
                            .addComponent(registrotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(registroedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Editorial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 10))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Telefono De La Editorial");

        registrotelefonoeditorial.setEnabled(false);
        registrotelefonoeditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrotelefonoeditorialActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Nombre De La Editorial");

        registronombreeditorial.setEnabled(false);
        registronombreeditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registronombreeditorialActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Direccion De La Editorial");

        registrodireccioneditorial.setEnabled(false);
        registrodireccioneditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodireccioneditorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrodireccioneditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrotelefonoeditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registronombreeditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(registrotelefonoeditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(registrodireccioneditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(registronombreeditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Autor\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 10))); // NOI18N
        jPanel4.setToolTipText("sadad");

        registronacionalidadautor.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Nacionalidad Del Autor");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Nombre Del Autor");

        registronombreautor.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registronacionalidadautor, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(registronombreautor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(registronacionalidadautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registronombreautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Secundario del Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 10))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Estado Del Libro");

        registroestadolibro.setEnabled(false);
        registroestadolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroestadolibroActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Genero Del Libro");

        registrogenerolibro.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Categoria Libro");

        registrocategorialibro.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Año De impresion");

        añodeimpresion.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registroestadolibro, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(registrogenerolibro)
                    .addComponent(registrocategorialibro)
                    .addComponent(añodeimpresion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(registroestadolibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(registrogenerolibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(registrocategorialibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(añodeimpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ingresoatras.setText("Atras");
        ingresoatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoatrasActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Valor/Precio del Libro");

        registropreciolibro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registropreciolibro.setEnabled(false);
        registropreciolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registropreciolibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(registropreciolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registropreciolibro, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(ingresoatras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addGap(186, 186, 186))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ingresoingresolibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ingresoingresolibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ingresoatras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Salir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel5.getAccessibleContext().setAccessibleName("Precio Libro");
        jPanel5.getAccessibleContext().setAccessibleDescription("");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("Sesión:");

        sesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sesion.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sesion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrodireccioneditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodireccioneditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrodireccioneditorialActionPerformed

    private void registronombreeditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registronombreeditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registronombreeditorialActionPerformed

    private void registrotelefonoeditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrotelefonoeditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrotelefonoeditorialActionPerformed

    private void botoningresolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoningresolibroActionPerformed
        // TODO add your handling code here:
        conexion cn=new conexion();
        String titulolibro=registrotitulo.getText();
        String edicion=registroedicion.getText();
        cn.setEsSelect(false);
        cn.setComandoSQL("insert into libro (titulo, edicion) values('"+titulolibro+"', '"+edicion+"')");
        cn.conectar();
        cn.cerrarConexion();
        cn.setEsSelect(false);
        if(titulolibro.length()>0 && edicion.length()>0){
        int respuesta = JOptionPane.showConfirmDialog(null, "El Libro fue ingresado exitosamente al sistema \n ¿Desea complementar la información?", "Confirmación de Ingreso", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);   
        //JOptionPane.showMessageDialog(this, "El libro fue agregado exitosamente \n Agregue más datos del libro o vuelva atras");
        if(respuesta==0){
        this.registrotitulo.disable();
        this.registroedicion.disable();
        this.registropreciolibro.enable();
        this.registrotelefonoeditorial.enable();
        this.registrodireccioneditorial.enable();
        this.registronombreautor.enable();
        this.registronacionalidadautor.enable();
        this.registroestadolibro.enable();
        this.registrogenerolibro.enable();
        this.registrocategorialibro.enable();
        this.añodeimpresion.enable();
        this.registronombreeditorial.enable();
        this.ingresoatras.disable();
        }
        else{
        int codigo=0;
        cn.setEsSelect(true);
        cn.setComandoSQL("select codigo_libro from libro where libro.codigo_libro=(select max(libro.codigo_libro) from libro)");
        cn.conectar();
        try {
            while(cn.getRst().next()){
                codigo=cn.getRst().getInt("codigo_libro");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaRegistroLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
        cn.cerrarConexion();
        
        int cod_user=0;
        String usuario=sesion.getText();
        cn.setEsSelect(true);
        cn.setComandoSQL("select cod_usuario from usuario where usuarioingreso='"+usuario+"'");
        cn.conectar();
        try {
            while(cn.getRst().next()){
                cod_user=cn.getRst().getInt("cod_usuario");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaRegistroLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
        cn.cerrarConexion();
        
        String preciolibro=registropreciolibro.getText();
        String nomeditorial=registronombreeditorial.getText();
        String teleditorial=registrotelefonoeditorial.getText();
        String direceditorial=registrodireccioneditorial.getText();
        String nombautor=registronombreautor.getText();
        String nacioautor=registronacionalidadautor.getText();
        String estadolibro=registroestadolibro.getText();
        String generolibro=registrogenerolibro.getText();
        String categorialibro=registrocategorialibro.getText();
        String añoimpresion=añodeimpresion.getText();
        
        cn.setEsSelect(false);
            cn.setComandoSQL("insert into editorial (nombre, telefono, direccion, cod_libro) values('"+nomeditorial+"', '"+teleditorial+"', '"+direceditorial+"','"+codigo+"')");
            cn.conectar();
            cn.cerrarConexion();
            cn.setComandoSQL("insert into autor (nombre, nacionalidad,cod_libro) values('"+nombautor+"', '"+nacioautor+"','"+codigo+"')");
            cn.conectar();
            cn.cerrarConexion();
            cn.setComandoSQL("insert into estado (nombre_estado, cod_libro) values('"+estadolibro+"','"+codigo+"')");
            cn.conectar();
            cn.cerrarConexion();
            cn.setComandoSQL("insert into genero (nombre,cod_libro) values('"+generolibro+"','"+codigo+"')");
            cn.conectar();
            cn.cerrarConexion();
            cn.setComandoSQL("insert into categoria (nombre_categoria,cod_libro) values('"+categorialibro+"','"+codigo+"')");
            cn.conectar();
            cn.cerrarConexion();
            cn.setComandoSQL("insert into libro_autor(año_impresion, codigo_usuario, codigo_libro,precio) values('"+añoimpresion+"','"+cod_user+"','"+codigo+"','"+preciolibro+"')");
            cn.conectar();
            cn.cerrarConexion();
            this.dispose();
        }
        }
        else
        javax.swing.JOptionPane.showMessageDialog (null, "Hay datos faltantes", "Registro Libro", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botoningresolibroActionPerformed

    private void ingresoingresolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoingresolibroActionPerformed
        // TODO add your handling code here:
        conexion cn=new conexion();
        int codigo=0;
        cn.setEsSelect(true);
        cn.setComandoSQL("select codigo_libro from libro where libro.codigo_libro=(select max(libro.codigo_libro) from libro)");
        cn.conectar();
        try {
            while(cn.getRst().next()){
                codigo=cn.getRst().getInt("codigo_libro");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaRegistroLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
        cn.cerrarConexion();
        
        int cod_user=0;
        String usuario=sesion.getText();
        cn.setEsSelect(true);
        cn.setComandoSQL("select cod_usuario from usuario where usuarioingreso='"+usuario+"'");
        cn.conectar();
        try {
            while(cn.getRst().next()){
                cod_user=cn.getRst().getInt("cod_usuario");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaRegistroLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
        cn.cerrarConexion();
        
        
        
        String preciolibro=registropreciolibro.getText();
        String nomeditorial=registronombreeditorial.getText();
        String teleditorial=registrotelefonoeditorial.getText();
        String direceditorial=registrodireccioneditorial.getText();
        String nombautor=registronombreautor.getText();
        String nacioautor=registronacionalidadautor.getText();
        String estadolibro=registroestadolibro.getText();
        String generolibro=registrogenerolibro.getText();
        String categorialibro=registrocategorialibro.getText();
        String añoimpresion=añodeimpresion.getText();
        
        if(nomeditorial.length()>0 && teleditorial.length()>0 && direceditorial.length()>0
            && nombautor.length()>0 && nacioautor.length()>0 && estadolibro.length()>0 && generolibro.length()>0 && categorialibro.length()>0
            && añoimpresion.length()>0  ){

            cn.setEsSelect(false);
            cn.setComandoSQL("insert into editorial (nombre, telefono, direccion, cod_libro) values('"+nomeditorial+"', '"+teleditorial+"', '"+direceditorial+"','"+codigo+"')");
            cn.conectar();
            cn.cerrarConexion();
            cn.setComandoSQL("insert into autor (nombre, nacionalidad,cod_libro) values('"+nombautor+"', '"+nacioautor+"','"+codigo+"')");
            cn.conectar();
            cn.cerrarConexion();
            cn.setComandoSQL("insert into estado (nombre_estado, cod_libro) values('"+estadolibro+"','"+codigo+"')");
            cn.conectar();
            cn.cerrarConexion();
            cn.setComandoSQL("insert into genero (nombre,cod_libro) values('"+generolibro+"','"+codigo+"')");
            cn.conectar();
            cn.cerrarConexion();
            cn.setComandoSQL("insert into categoria (nombre_categoria,cod_libro) values('"+categorialibro+"','"+codigo+"')");
            cn.conectar();
            cn.cerrarConexion();
            cn.setComandoSQL("insert into libro_autor(año_impresion, codigo_usuario, codigo_libro,precio) values('"+añoimpresion+"','"+cod_user+"','"+codigo+"','"+preciolibro+"')");
            cn.conectar();
            cn.cerrarConexion();
            JOptionPane.showMessageDialog(this, "Se agregaron correctamente los datos");
            this.dispose();
            
        }
        else{
            javax.swing.JOptionPane.showMessageDialog (null, "Hay datos faltantes", "Ficha de Registro", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ingresoingresolibroActionPerformed

    private void registroestadolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroestadolibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroestadolibroActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Realmente desea salir del sistema?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0){        System.exit(0);   
        }// TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void ingresoatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoatrasActionPerformed
       int respuesta = JOptionPane.showConfirmDialog(null, "Quedan datos por llenar, ¿Realmente quiere volver atras?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0){
            this.dispose(); 
        }
        
        
  // TODO add your handling code here:
    }//GEN-LAST:event_ingresoatrasActionPerformed

    private void registrotituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrotituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrotituloActionPerformed

    private void registropreciolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registropreciolibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registropreciolibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Salir;
    public javax.swing.JTextField añodeimpresion;
    public javax.swing.JButton botoningresolibro;
    public javax.swing.JButton ingresoatras;
    public javax.swing.JButton ingresoingresolibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JTextField registrocategorialibro;
    public javax.swing.JTextField registrodireccioneditorial;
    public javax.swing.JTextField registroedicion;
    public javax.swing.JTextField registroestadolibro;
    public javax.swing.JTextField registrogenerolibro;
    public javax.swing.JTextField registronacionalidadautor;
    public javax.swing.JTextField registronombreautor;
    public javax.swing.JTextField registronombreeditorial;
    private javax.swing.JTextField registropreciolibro;
    public javax.swing.JTextField registrotelefonoeditorial;
    public javax.swing.JTextField registrotitulo;
    public javax.swing.JLabel sesion;
    private javax.swing.JLabel titulolibro;
    // End of variables declaration//GEN-END:variables
}
